# This workflow will do a clean install of node dependencies, build the application and deploy it to production

name: Build & Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17
      uses: actions/setup-node@v1
      with:
        node-version: 17.x
    - name: Build app using Yarn
      run: |
        npm install -g yarn
        yarn install
        yarn build
    - name: Push Build files to production
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        port: ${{ secrets.DEPLOY_PORT }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        passphrase: ${{ secrets.DEPLOY_SSH_PHRASE }}
        source: dist/*
        target: ${{ secrets.DEPLOY_PATH }}
        rm: true
